# Zoomcamp Homework - 01 intro

##Getting the data

In [272]:
import pandas as pd
import numpy as np

df = pd.read_csv("housing.csv", delimiter=',', low_memory=False)

## Number of columns in dataframe

In [273]:
df.shape

(20640, 10)

## Which columns in the dataset have missing values?

In [274]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## How many unique values does the ocean_proximity column have?

In [275]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

## What's the average value of the median_house_value for the houses located near the bay?

In [276]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].describe()

count      2290.000000
mean     259212.311790
std      122818.537064
min       22500.000000
25%      162500.000000
50%      233800.000000
75%      345700.000000
max      500001.000000
Name: median_house_value, dtype: float64

## Fill the missing values in total_bedrooms with the mean value

In [277]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)
df['total_bedrooms'].mean()

537.8705525375617

## Apply Transposition

1) Select all the options located on islands.
2) Select only columns housing_median_age, total_rooms, total_bedrooms.
3) Get the underlying NumPy array. Let's call it X.
4) Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5) Compute the inverse of XTX.
6) Create an array y with values [950, 1300, 800, 1000, 1300].
7) Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8) What's the value of the last element of w?

In [278]:
island = df[df['ocean_proximity'] == 'ISLAND']
X = island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
X.shape

(5, 3)

In [279]:
XTX = np.dot(X.T, X)

In [280]:
X.head(5)

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [281]:
X.T

8314    8315    8316   8317   8318
housing_median_age    27.0    52.0    52.0   52.0   29.0
total_rooms         1675.0  2359.0  2127.0  996.0  716.0
total_bedrooms       521.0   591.0   512.0  264.0  214.0

In [282]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [283]:
def compute_inverse(X):
    try:
        inverse_matrix = np.linalg.inv(X)
        print("Inverse Matrix:")
    except np.linalg.LinAlgError:
        print("Matrix is singular; the inverse does not exist.")
    return inverse_matrix

inverse_df = compute_inverse(XTX)
print(inverse_df)

Inverse Matrix:
[[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [284]:
y = [950, 1300, 800, 1000, 1300]

a = np.dot(X.T, inverse_df)
w = np.dot(a, y)

print(w)

In [285]:
# Calculate X_transpose_y (X transpose multiplied by y)
X_transpose_y = np.dot(X.T, y)

# Calculate w by multiplying XTX_inverse with X_transpose_y
w = np.dot(inverse_df, X_transpose_y)

print(w)

[23.12330961 -1.48124183  5.69922946]
